hw21
Holotova/First pull request #15
Opened 2022-05-27 17:12 UTC by Holotova

2022-05-28 15:32 UTC, Fabolo12 requested changes
Нет зависимости на рефлексию в pom

Доделай дз, ты почти его закончила, надо всего пару мелких правок внести

2022-05-28 15:32 UTC, Fabolo12 commented on src/main/java/ua/holotova/hw21/AnnotationCheckService.java
> +                    field.set(pet, (Integer)field.get(pet)*3);
Ты пытаешься установить значение в Класс, а надо в Обьект класса

2022-05-28 15:32 UTC, Fabolo12 commented on src/main/java/ua/holotova/hw21/AnnotationCheckService.java
> +                    field.set(pet, (Integer)field.get(pet)*3);
Так же нет проверки на тип поля

2022-05-28 15:32 UTC, Fabolo12 commented on src/main/java/ua/holotova/hw21/AnnotationCheckService.java
> +            Method[] methods = myPets.values().getClass().getDeclaredMethods();
Тут ты работаешь не со своими обьектами, посмотрм в дебаге

2022-06-29 22:40 UTC, Holotova commented
Доделала ДЗ 21

2022-07-03 19:02 UTC, Fabolo12 approved these changes

2022-07-03 19:47 UTC, merged